apiVersion: v1
kind: Service
metadata:
  name: spring-order-lb
spec:
  type: ClusterIP
  selector:
    app: spring-order
  ports:
    - name: spring-order
      protocol: TCP
      port: 80
      targetPort: 8080
