apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: 611155787285.dkr.ecr.ap-northeast-2.amazonaws.com/java_cloudladder
  newName: 611155787285.dkr.ecr.ap-northeast-2.amazonaws.com/java_cloudladder
  newTag: 2b0dc779b13262dd9f631e9dc5826a5afc065442
